theme: jekyll-theme-minimal
title: Denver Urban Gardens Locations & Food Access
description: How are DUG community gardens distributed? And how does that compare with the distribution of low-income, low-food-access areas in Denver?
