title: Denver: DUG Locations & Food Access
description: This mapping project aims to answer the question: how does the distribution of DUG community gardens look compared with the distribution of low-food-access areas in Denver?
