theme: jekyll-theme-minimal
title: Denver Urban Gardens Locations & Food Access
description: How does the distribution of DUG community gardens look compared with the distribution of low-food-access areas in Denver?
